### ISSUE TITLE
contributing template too long - would not read

### ISSUE THREAD

**Issue by mattearly** [nayafia/contributing-template#12]
"Be concise. Adding too much detail might actually make people less likely to read your guide, which will defeat the purpose."

I'll show myself out...

**Comment by nayafia** [comment]
Ha! Thanks for pointing this out 😉The goal of the template is to provide a checklist of everything you may want to consider including, depending on the complexity of your project. Ideally, someone would only include the sections that they absolutely need.

From the README:

> This template is meant to be a checklist to make sure you haven’t missed anything, rather than offering guidance on philosophy or approach. Your final guidelines may differ depending on your project and needs.
