### ISSUE TITLE
contributing template in spanish

### ISSUE THREAD

**Issue by valerybriz** [nayafia/contributing-template#14]
This template helped a lot the organization I work with and also my own side open source projects I think It might help a lot of people that doesn't speak english and also maintains foss projects.

I would like to completely translate this guide so you can have it able also in spanish.

What you think? Can I help with that?

**Comment by nayafia** [comment]
Hi @valerybriz, absolutely! 😊 Feel free to translate on a new repo and submit a PR to link from this one when ready. Can follow a format like this one: https://github.com/nayafia/lemonade-stand for listing out translations.

**Comment by valerybriz** [comment]
Awesome! I'll be working on it :)

**Comment by valerybriz** [comment]
Hey! I just submited a pull request with the traslation on #15

**Comment by nayafia** [comment]
Closing here to continue discussion on #15
