### ISSUE TITLE
Permission to base a contributing.md template on this repo

### ISSUE THREAD

**Issue by jameswomack** [nayafia/contributing-template#3]
Hi there. 

I'm planning on re-releasing a tool named Unleash under the Netflix brand soon. It was previously released under my own name at https://github.com/jameswomack/unleash 

I'd like to make Unleash better by including additional pieces that a software project needs to be successful, including a "contributing" file. Your project looks like a good one to base it on, and I'd like your permission to do so.

**Comment by danielskatz** [comment]
The license for this repo says you already have permission.

**Comment by jameswomack** [comment]
You're right! Thanks.

**Comment by nayafia** [comment]
Thanks for asking, and looking forward to seeing the release! I added license info to the readme to make this more explicit: https://github.com/nayafia/contributing-template/commit/782e33eb328e003f3d3e5941267728fcdad1f914
